### PR TITLE
Add the ability to selectively disable segments

### PR DESCRIPTION
**Pull request by MichaelAquilina**
Allow selective disabling of prompts if the user does not wish them to be displayed. 

All it requires is for an appropriate environment variable to be set.

### CODE REVIEW

**Comment by apjanke** [comment]
If you're going to start adding options, instead of several separate `$AGNOSTER_*` scalar variables, would you consider making a single `$AGNOSTER_OPTS` associative array variable? And maybe making it hidden with `-H`, so it doesn't clutter up the output of `set`? Might be easier to work with, and could become nice if you end up adding options which can accept terminal-control characters in their values. (E.g. like this: https://github.com/robbyrussell/oh-my-zsh/pull/3965.)

**Comment by MichaelAquilina** [comment]
Thanks for the input @apjanke, will look into it :) Any thoughts @agnoster ?

**Comment by MichaelAquilina** [comment]
@agnoster polite ping on this

**Comment by agnoster** [comment]
I definitely like @apjanke's suggestion of making it a single (hidden) options value - what I'd actually love is to make it a single array that specified the desired segments in the order they should appear, with a default value of "all segments, in the current order". One nice aspect of this is that we could add support for more types of segments and let users choose which ones should go where, without doing special hard-coding - instead simply looping over the array and rendering each segment.

But that's a bigger undertaking, and shamefully I don't think my zsh-fu is gonna be up to the task.

**Comment by MichaelAquilina** [comment]
I dont think it would be too complicated actually. I was already thinking of taking that approach just felt like this would be a nice first step instead. I can try find the time to do this as soon as I get the chance but I have quite a few other things I am working on atm.

**Review by steelrooter — APPROVED** [review]

**Comment by apodkutin** [comment]
@agnoster, @apjanke, @MichaelAquilina please have a look on this PR https://github.com/agnoster/agnoster-zsh-theme/pull/91

**Comment by apjanke** [comment]
I like it!

**Pull request closed without merging**
