### PR TITLE
Add the prompt view customization ability

### PR DESCRIPTION
**Pull request by apodkutin**
By default prompt has these segments: `prompt_status`, `prompt_context`, `prompt_virtualenv`, `prompt_dir`, `prompt_git`, `prompt_end` in that particular order.

If you want to add, change the order or remove some segments of the prompt, you can use array environment variable named `AGNOSTER_PROMPT_SEGMENTS`.

Examples:
- Show all segments of the prompt with indices:
```
echo "${(F)AGNOSTER_PROMPT_SEGMENTS[@]}" | cat -n
```
- Add the new segment of the prompt to the beginning:
```
AGNOSTER_PROMPT_SEGMENTS=("prompt_git" "${AGNOSTER_PROMPT_SEGMENTS[@]}")
```
- Add the new segment of the prompt to the end:
```
AGNOSTER_PROMPT_SEGMENTS+="prompt_end"
```
- Insert the new segment of the prompt = `PROMPT_SEGMENT_NAME` on the particular position = `PROMPT_SEGMENT_POSITION`:
```
PROMPT_SEGMENT_POSITION=5 PROMPT_SEGMENT_NAME="prompt_end";\
AGNOSTER_PROMPT_SEGMENTS=("${AGNOSTER_PROMPT_SEGMENTS[@]:0:$PROMPT_SEGMENT_POSITION-1}" "$PROMPT_SEGMENT_NAME" "${AGNOSTER_PROMPT_SEGMENTS[@]:$PROMPT_SEGMENT_POSITION-1}");\
unset PROMPT_SEGMENT_POSITION PROMPT_SEGMENT_NAME
```
- Swap segments 4th and 5th:
```
SWAP_SEGMENTS=(4 5);\
TMP_VAR="$AGNOSTER_PROMPT_SEGMENTS[$SWAP_SEGMENTS[1]]"; AGNOSTER_PROMPT_SEGMENTS[$SWAP_SEGMENTS[1]]="$AGNOSTER_PROMPT_SEGMENTS[$SWAP_SEGMENTS[2]]"; AGNOSTER_PROMPT_SEGMENTS[$SWAP_SEGMENTS[2]]="$TMP_VAR"
unset SWAP_SEGMENTS TMP_VAR
```
- Remove the 5th segment:
```
AGNOSTER_PROMPT_SEGMENTS[5]=
```

A small demo of the dummy custom prompt segment, which has been created with help of the built-in `prompt_segment()` function from Agnoster theme:
```
# prompt_segment() - Takes two arguments, background and foreground.
# Both can be omitted, rendering default background/foreground.

customize_agnoster() {
  prompt_segment 'red' '' ' ⚙ ⚡⚡⚡ ⚙  '
}
```
Customization demo

### CODE REVIEW

**Comment by apjanke** [comment]
I like it! This looks like a good approach to making the whole prompt more customizable.

One niggle: I would personally call the variable `AGNOSTER_PROMPT_SEGMENTS` instead of `AGNOSTER_PROMPT`, since a `<foo>_PROMPT` variable is usually a single formatted non-array string variable that defines a prompt, instead of an array.

Really good PR write-up too; kudos to you.

**Comment by agnoster** [comment]
Yes, this looks great! I agree with @apjanke re: naming, (`AGNOSTER_PROMPT_SEGMENTS` would be a better name for the config variable), with that change I'd be happy to merge.

Also +1 to the write-up.

**Comment by apodkutin** [comment]
@apjanke, @agnoster Thank you guys! 
I will do it today.

**Review by MichaelAquilina — APPROVED** [review]
Excellent work @apodkutin :)

**Comment by apodkutin** [comment]
Thank you @MichaelAquilina !
@apjanke, @agnoster PR has been updated.

There is also PR in oh-my-zsh repository, if you are interested in https://github.com/robbyrussell/oh-my-zsh/pull/7355

**Review by agnoster — APPROVED** [review]
Thanks so much for this!

I'm thinking about maybe tweaking it slightly in future - I would like for the config to be something like a format string, like `status>context>virtualenv>dir>git>` (with `end` being automatic, I can't think of a situation where you wouldn't want the prompt to be closed ;-)) But for now I think this is already far better than what we had!

**Comment by agnoster** [comment]
Small note: it looks like in the GIF demo there's something wrong with the color of the triangular segments - the very first one should be blue to match the directory, but appears black in the capture. Which terminal / color scheme are you using? I don't think it's related to the change here, but it'd be nice if the GIF demonstrating the feature had the right colors. For an example of what the prompt ought to look like, see:

Reference Screenshot

**Comment by apodkutin** [comment]
Good catch @agnoster, I'm using iterm2/Solarized dark. I will fix it and will make a new recording of the demo.

And about your proposal regarding `status>context>virtualenv>dir>git>` config, I will try to implement it in the next PR.

**Comment by apodkutin** [comment]
@agnoster, GIF demo recording has been updated.

**Comment by agnoster** [comment]
Thanks again, this is wonderful!

**Pull request merged**
